apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prokopev-certificate
spec:
  dnsNames:
  - 'prokopev.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: prokopev-cert